### ISSUE TITLE
CI/CD Pipeline

### ISSUE THREAD

**Issue by ChristopherJMiller** [realliance/senior-game#2]
Concourse CI PR validation and Artifact Release Pipelines should be constructed and deployed.

**Comment by ChristopherJMiller** [comment]
Feature put on hold until [unityci/editor](https://hub.docker.com/r/unityci/editor/tags?page=1&ordering=last_updated&name=2021) images is updated with a Unity `2021.1.0b1` tag. This issue will reopen if the tag becomes available or in 2 weeks, at which point the image repo will be forked and be done ourselves.

**Comment by ConnorJC3** [comment]
Reopening, CI pipeline does not build a server image
